// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: destiny_player.sql

package db

import (
	"context"
	"database/sql"
)

const createDestinyPlayer = `-- name: CreateDestinyPlayer :exec
INSERT INTO destiny_player (
    membership_id,
    membership_type,
    icon_path,
    display_name,
    global_display_name,
    global_display_name_code,
    total_clears,
    total_full_clears,
    is_private,
    last_crawled,
    last_seen
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
`

type CreateDestinyPlayerParams struct {
	MembershipID          int64          `json:"membership_id"`
	MembershipType        int32          `json:"membership_type"`
	IconPath              sql.NullString `json:"icon_path"`
	DisplayName           sql.NullString `json:"display_name"`
	GlobalDisplayName     sql.NullString `json:"global_display_name"`
	GlobalDisplayNameCode sql.NullInt32  `json:"global_display_name_code"`
	TotalClears           int32          `json:"total_clears"`
	TotalFullClears       int32          `json:"total_full_clears"`
	IsPrivate             sql.NullBool   `json:"is_private"`
	LastCrawled           interface{}    `json:"last_crawled"`
	LastSeen              interface{}    `json:"last_seen"`
}

func (q *Queries) CreateDestinyPlayer(ctx context.Context, arg CreateDestinyPlayerParams) error {
	_, err := q.exec(ctx, q.createDestinyPlayerStmt, createDestinyPlayer,
		arg.MembershipID,
		arg.MembershipType,
		arg.IconPath,
		arg.DisplayName,
		arg.GlobalDisplayName,
		arg.GlobalDisplayNameCode,
		arg.TotalClears,
		arg.TotalFullClears,
		arg.IsPrivate,
		arg.LastCrawled,
		arg.LastSeen,
	)
	return err
}
