// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance.sql

package db

import (
	"context"
	"time"
)

const createInstance = `-- name: CreateInstance :exec
INSERT INTO instance (
    id,
    activity_hash,
    is_fresh,
    flawless,
    completed,
    player_count,
    duration_seconds,
    end_time,
    start_time
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateInstanceParams struct {
	ID              int64     `json:"id"`
	ActivityHash    int64     `json:"activity_hash"`
	IsFresh         bool      `json:"is_fresh"`
	Flawless        bool      `json:"flawless"`
	Completed       bool      `json:"completed"`
	PlayerCount     int32     `json:"player_count"`
	DurationSeconds int32     `json:"duration_seconds"`
	EndTime         time.Time `json:"end_time"`
	StartTime       time.Time `json:"start_time"`
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) error {
	_, err := q.exec(ctx, q.createInstanceStmt, createInstance,
		arg.ID,
		arg.ActivityHash,
		arg.IsFresh,
		arg.Flawless,
		arg.Completed,
		arg.PlayerCount,
		arg.DurationSeconds,
		arg.EndTime,
		arg.StartTime,
	)
	return err
}
