// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance_character_weapon.sql

package db

import (
	"context"
)

const createInstanceCharacterWeapon = `-- name: CreateInstanceCharacterWeapon :exec
INSERT INTO instance_character_weapon (
    instance_id,
    player_membership_id,
    player_character_id,
    weapon_id,
    kills,
    precision_kills,
    precision_ratio
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT DO NOTHING
RETURNING instance_id
`

type CreateInstanceCharacterWeaponParams struct {
	InstanceID         int64  `json:"instance_id"`
	PlayerMembershipID int64  `json:"player_membership_id"`
	PlayerCharacterID  int64  `json:"player_character_id"`
	WeaponID           int64  `json:"weapon_id"`
	Kills              int32  `json:"kills"`
	PrecisionKills     int32  `json:"precision_kills"`
	PrecisionRatio     string `json:"precision_ratio"`
}

func (q *Queries) CreateInstanceCharacterWeapon(ctx context.Context, arg CreateInstanceCharacterWeaponParams) error {
	_, err := q.exec(ctx, q.createInstanceCharacterWeaponStmt, createInstanceCharacterWeapon,
		arg.InstanceID,
		arg.PlayerMembershipID,
		arg.PlayerCharacterID,
		arg.WeaponID,
		arg.Kills,
		arg.PrecisionKills,
		arg.PrecisionRatio,
	)
	return err
}
