// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance_player.sql

package db

import (
	"context"
	"database/sql"
)

const createInstancePlayer = `-- name: CreateInstancePlayer :exec
INSERT INTO instance_player (
    instance_id,
    membership_id,
    completed,
    time_played_seconds
) VALUES (
    $1,
    $2,
    $3,
    $4
) ON CONFLICT (instance_id, membership_id) DO NOTHING
`

type CreateInstancePlayerParams struct {
	InstanceID        int64        `json:"instance_id"`
	MembershipID      int64        `json:"membership_id"`
	Completed         sql.NullBool `json:"completed"`
	TimePlayedSeconds int32        `json:"time_played_seconds"`
}

func (q *Queries) CreateInstancePlayer(ctx context.Context, arg CreateInstancePlayerParams) error {
	_, err := q.exec(ctx, q.createInstancePlayerStmt, createInstancePlayer,
		arg.InstanceID,
		arg.MembershipID,
		arg.Completed,
		arg.TimePlayedSeconds,
	)
	return err
}
