// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance_character.sql

package db

import (
	"context"
)

const createInstanceCharacter = `-- name: CreateInstanceCharacter :exec
INSERT INTO instance_character (
    instance_id,
    membership_id,
    character_id,
    emblem_hash,
    class_hash,
    completed,
    kills,
    deaths,
    assists,
    kda,
    kdr,
    super_kills,
    melee_kills,
    grenade_kills,
    efficiency,
    time_played_seconds
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
ON CONFLICT (instance_id, membership_id, character_id) DO NOTHING
RETURNING instance_id
`

type CreateInstanceCharacterParams struct {
	InstanceID        int64  `json:"instance_id"`
	MembershipID      int64  `json:"membership_id"`
	CharacterID       int64  `json:"character_id"`
	EmblemHash        int64  `json:"emblem_hash"`
	ClassHash         int64  `json:"class_hash"`
	Completed         bool   `json:"completed"`
	Kills             int32  `json:"kills"`
	Deaths            int32  `json:"deaths"`
	Assists           int32  `json:"assists"`
	Kda               string `json:"kda"`
	Kdr               string `json:"kdr"`
	SuperKills        int32  `json:"super_kills"`
	MeleeKills        int32  `json:"melee_kills"`
	GrenadeKills      int32  `json:"grenade_kills"`
	Efficiency        int32  `json:"efficiency"`
	TimePlayedSeconds int32  `json:"time_played_seconds"`
}

func (q *Queries) CreateInstanceCharacter(ctx context.Context, arg CreateInstanceCharacterParams) error {
	_, err := q.exec(ctx, q.createInstanceCharacterStmt, createInstanceCharacter,
		arg.InstanceID,
		arg.MembershipID,
		arg.CharacterID,
		arg.EmblemHash,
		arg.ClassHash,
		arg.Completed,
		arg.Kills,
		arg.Deaths,
		arg.Assists,
		arg.Kda,
		arg.Kdr,
		arg.SuperKills,
		arg.MeleeKills,
		arg.GrenadeKills,
		arg.Efficiency,
		arg.TimePlayedSeconds,
	)
	return err
}
