// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: log.sql

package db

import (
	"context"
	"database/sql"
)

const updateLogEntryStatus = `-- name: UpdateLogEntryStatus :exec
UPDATE ingestion_log
SET
    status = $2,
    last_attempt_at = now(),
    error = $3
WHERE instance_id = $1
`

type UpdateLogEntryStatusParams struct {
	InstanceID int64          `json:"instance_id"`
	Status     string         `json:"status"`
	Error      sql.NullString `json:"error"`
}

func (q *Queries) UpdateLogEntryStatus(ctx context.Context, arg UpdateLogEntryStatusParams) error {
	_, err := q.exec(ctx, q.updateLogEntryStatusStmt, updateLogEntryStatus, arg.InstanceID, arg.Status, arg.Error)
	return err
}

const upsertLogEntry = `-- name: UpsertLogEntry :one
INSERT INTO ingestion_log (instance_id, source, status)
VALUES ($1, $2, $3)
ON CONFLICT (instance_id) DO UPDATE
    SET
        last_attempt_at = now(),
        attempt_count = ingestion_log.attempt_count + 1
RETURNING instance_id, source, status, first_seen_at, last_attempt_at, attempt_count, error
`

type UpsertLogEntryParams struct {
	InstanceID int64  `json:"instance_id"`
	Source     string `json:"source"`
	Status     string `json:"status"`
}

func (q *Queries) UpsertLogEntry(ctx context.Context, arg UpsertLogEntryParams) (IngestionLog, error) {
	row := q.queryRow(ctx, q.upsertLogEntryStmt, upsertLogEntry, arg.InstanceID, arg.Source, arg.Status)
	var i IngestionLog
	err := row.Scan(
		&i.InstanceID,
		&i.Source,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastAttemptAt,
		&i.AttemptCount,
		&i.Error,
	)
	return i, err
}
