// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Activity struct {
	ActivityHash  int64        `json:"activity_hash"`
	ActivityLabel string       `json:"activity_label"`
	NameID        int64        `json:"name_id"`
	DifficultyID  int64        `json:"difficulty_id"`
	IsWorldsFirst sql.NullBool `json:"is_worlds_first"`
}

type ActivityDifficulty struct {
	ID            int64  `json:"id"`
	ActivityLabel string `json:"activity_label"`
}

type ActivityName struct {
	ID            int64     `json:"id"`
	ActivityLabel string    `json:"activity_label"`
	IsActive      bool      `json:"is_active"`
	ReleaseDate   time.Time `json:"release_date"`
}

type DestinyPlayer struct {
	MembershipID          int64          `json:"membership_id"`
	MembershipType        int32          `json:"membership_type"`
	IconPath              sql.NullString `json:"icon_path"`
	DisplayName           sql.NullString `json:"display_name"`
	GlobalDisplayName     sql.NullString `json:"global_display_name"`
	GlobalDisplayNameCode sql.NullInt32  `json:"global_display_name_code"`
	TotalClears           int32          `json:"total_clears"`
	TotalFullClears       int32          `json:"total_full_clears"`
	IsPrivate             sql.NullBool   `json:"is_private"`
	LastCrawled           interface{}    `json:"last_crawled"`
	LastSeen              interface{}    `json:"last_seen"`
	CreatedAt             interface{}    `json:"created_at"`
}

type IngestionLog struct {
	InstanceID    int64          `json:"instance_id"`
	Source        string         `json:"source"`
	Status        string         `json:"status"`
	FirstSeenAt   time.Time      `json:"first_seen_at"`
	LastAttemptAt time.Time      `json:"last_attempt_at"`
	AttemptCount  int32          `json:"attempt_count"`
	Error         sql.NullString `json:"error"`
}

type Instance struct {
	ID              int64       `json:"id"`
	ActivityHash    int64       `json:"activity_hash"`
	IsFresh         bool        `json:"is_fresh"`
	Flawless        bool        `json:"flawless"`
	Completed       bool        `json:"completed"`
	PlayerCount     int32       `json:"player_count"`
	DurationSeconds int32       `json:"duration_seconds"`
	EndTime         interface{} `json:"end_time"`
	StartTime       interface{} `json:"start_time"`
	CreatedAt       interface{} `json:"created_at"`
}

type InstanceCharacter struct {
	InstanceID        int64  `json:"instance_id"`
	MembershipID      int64  `json:"membership_id"`
	CharacterID       int64  `json:"character_id"`
	ClassHash         int64  `json:"class_hash"`
	EmblemHash        int64  `json:"emblem_hash"`
	Completed         bool   `json:"completed"`
	Kills             int32  `json:"kills"`
	Deaths            int32  `json:"deaths"`
	Assists           int32  `json:"assists"`
	Kda               string `json:"kda"`
	Kdr               string `json:"kdr"`
	SuperKills        int32  `json:"super_kills"`
	MeleeKills        int32  `json:"melee_kills"`
	GrenadeKills      int32  `json:"grenade_kills"`
	Efficiency        int32  `json:"efficiency"`
	TimePlayedSeconds int32  `json:"time_played_seconds"`
}

type InstanceCharacterWeapon struct {
	InstanceID         int64  `json:"instance_id"`
	PlayerMembershipID int64  `json:"player_membership_id"`
	PlayerCharacterID  int64  `json:"player_character_id"`
	WeaponID           int64  `json:"weapon_id"`
	Kills              int32  `json:"kills"`
	PrecisionKills     int32  `json:"precision_kills"`
	PrecisionRatio     string `json:"precision_ratio"`
}

type InstancePlayer struct {
	InstanceID        int64        `json:"instance_id"`
	MembershipID      int64        `json:"membership_id"`
	Completed         sql.NullBool `json:"completed"`
	TimePlayedSeconds int32        `json:"time_played_seconds"`
	CreatedAt         interface{}  `json:"created_at"`
}

type Pgcr struct {
	InstanceID int64     `json:"instance_id"`
	Blob       []byte    `json:"blob"`
	CreatedAt  time.Time `json:"created_at"`
}

type Weapon struct {
	WeaponHash    int64  `json:"weapon_hash"`
	IconUrl       string `json:"icon_url"`
	WeaponName    string `json:"weapon_name"`
	EquipmentSlot string `json:"equipment_slot"`
	DamageType    string `json:"damage_type"`
}
