// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pgcr.sql

package db

import (
	"context"
)

const createPgcr = `-- name: CreatePgcr :exec
INSERT INTO pgcr (
    instance_id,
    blob
)
VALUES (
    $1,
    $2
)
`

type CreatePgcrParams struct {
	InstanceID int64  `json:"instance_id"`
	Blob       []byte `json:"blob"`
}

func (q *Queries) CreatePgcr(ctx context.Context, arg CreatePgcrParams) error {
	_, err := q.exec(ctx, q.createPgcrStmt, createPgcr, arg.InstanceID, arg.Blob)
	return err
}
