// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateDestinyPlayer(ctx context.Context, arg CreateDestinyPlayerParams) error
	CreateInstance(ctx context.Context, arg CreateInstanceParams) error
	CreateInstanceCharacter(ctx context.Context, arg CreateInstanceCharacterParams) error
	CreateInstanceCharacterWeapon(ctx context.Context, arg CreateInstanceCharacterWeaponParams) error
	CreateInstancePlayer(ctx context.Context, arg CreateInstancePlayerParams) error
	CreatePgcr(ctx context.Context, arg CreatePgcrParams) error
	CreateWeapon(ctx context.Context, arg CreateWeaponParams) error
}

var _ Querier = (*Queries)(nil)
