// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weapon.sql

package db

import (
	"context"
)

const createWeapon = `-- name: CreateWeapon :exec
INSERT INTO weapon (
    weapon_hash,
    icon_url,
    weapon_name,
    damage_type,
    equipment_slot
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateWeaponParams struct {
	WeaponHash    int64  `json:"weapon_hash"`
	IconUrl       string `json:"icon_url"`
	WeaponName    string `json:"weapon_name"`
	DamageType    string `json:"damage_type"`
	EquipmentSlot string `json:"equipment_slot"`
}

func (q *Queries) CreateWeapon(ctx context.Context, arg CreateWeaponParams) error {
	_, err := q.exec(ctx, q.createWeaponStmt, createWeapon,
		arg.WeaponHash,
		arg.IconUrl,
		arg.WeaponName,
		arg.DamageType,
		arg.EquipmentSlot,
	)
	return err
}
